//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDElektrikEntities : DbContext
    {
        public BDElektrikEntities()
            : base("name=BDElektrikEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArizaKategori> ArizaKategori { get; set; }
        public virtual DbSet<Arizalar> Arizalar { get; set; }
        public virtual DbSet<Blog> Blog { get; set; }
        public virtual DbSet<Galeri> Galeri { get; set; }
        public virtual DbSet<Hakkimizda> Hakkimizda { get; set; }
        public virtual DbSet<iletisim> iletisim { get; set; }
        public virtual DbSet<MalzemeKategoriler> MalzemeKategoriler { get; set; }
        public virtual DbSet<Malzemeler> Malzemeler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<İletisimBilgileri> İletisimBilgileri { get; set; }
        public virtual DbSet<Referanslar> Referanslar { get; set; }
        public virtual DbSet<MüsteriKayıt> MüsteriKayıt { get; set; }
        public virtual DbSet<MüsteriYorumları> MüsteriYorumları { get; set; }
        public virtual DbSet<Login> Login { get; set; }
    }
}
