//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proje.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class MüsteriYorumları
    {
        public int id { get; set; }
        public int Müsteri_id { get; set; }
        public string Müsteri_Yorum { get; set; }
    }
}
